apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: {{ .Values.notifications.slackToken | default "PLACEHOLDER" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token

  template.on-deployed: |
    message: |
      :rocket: *Application {{ "{{" }} .app.metadata.name {{ "}}" }} has been deployed!*
      *Cluster*: {{ "{{" }} .context.argocd_url {{ "}}" }}
      *Status*: {{ "{{" }} .app.status.sync.status {{ "}}" }}
      *Sync Commit*: {{ "{{" }} .app.status.sync.revision {{ "}}" }}

  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [on-deployed]
