apiVersion: v1
kind: Service
metadata:
  name: opsboard-backend
  labels:
    app: opsboard-backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: opsboard-backend
