apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsboard-frontend
  labels:
    app: opsboard-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: opsboard-frontend
  template:
    metadata:
      labels:
        app: opsboard-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              name: http
