apiVersion: v1
kind: Service
metadata:
  name: opsboard-frontend
  labels:
    app: opsboard-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: opsboard-frontend
