apiVersion: v1
kind: Service
metadata:
  name: opsboard-postgres
  labels:
    app: opsboard-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: opsboard-postgres
