apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opsboard-postgres
  labels:
    app: opsboard-postgres
spec:
  serviceName: opsboard-postgres
  replicas: 1
  selector:
    matchLabels:
      app: opsboard-postgres
  template:
    metadata:
      labels:
        app: opsboard-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          envFrom:
            - secretRef:
                name: opsboard-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
