backend:
  image:
    repository: 379395160438.dkr.ecr.us-east-1.amazonaws.com/opsboard-backend
    tag: "prod-12"
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 8080
  servicePort: 8080

frontend:
  image:
    repository: 379395160438.dkr.ecr.us-east-1.amazonaws.com/opsboard-frontend
    tag: "prod-12"
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 80
  servicePort: 80

postgres:
  image:
    repository: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/opsboard-postgres
    tag: "prod-stable"
    pullPolicy: IfNotPresent
  port: 5432
  database: opsboard
  username: opsboard_user
  passwordPlaceholder: "replace-me"
  storageSize: 1Gi

ingress:
  enabled: true

config:
  springProfilesActive: "prod"

notifications:
  slackToken: "REPLACE_ME_IN_K8S_SECRET"
